# Generated by Django 4.2.17 on 2024-12-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PROVIDER', 'Provider')], default='CLIENT', max_length=10),
        ),
    ]
